# Font configuration (changes require restart)
font:
  size: 14
  # The normal (roman) font face to use.
  normal:
    family: inconsolata
    style: medium

  # The bold font face
  bold:
    family: inconsolata
    style: bold
  
  italic:
    family: inconsolata
    style: italic
   
shell:
  program: /bin/zsh


scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 3000

  # Number of lines the viewport will move for every line scrolled when
  # scrollback is enabled (history > 0).
  multiplier: 3

  # Faux Scrolling
  #
  # The `faux_multiplier` setting controls the number of lines the terminal
  # should scroll when the alternate screen buffer is active. This is used
  # to allow mouse scrolling for applications like `man`.
  #
  # Specifying `0` will disable faux scrolling.
  scroll_escape: 3

cursor:
  # Cursor style
  style:
    # Cursor shape
    #
    # Values for `shape`:
    #   - ▇ Block
    #   - _ Underline
    #   - | Beam
    shape: Block

    # Cursor blinking state
    #
    # Values for `blinking`:
    #   - Never: Prevent the cursor from ever blinking
    #   - Off: Disable blinking by default
    #   - On: Enable blinking by default
    #   - Always: Force the cursor to always blink
    blinking: Always
    interval: 500

    
# Opacity
window:
 opacity: 0.70

# Colors (Kitty)
colors:
  # Default colors
  primary:
    background: '#000000'
    foreground: '#dddddd'

  # Normal colors
  normal:
    black:   '#000000'
    red:     '#cc0403'
    green:   '#19cb00'
    yellow:  '#cecb00'
    blue:    '#0d73cc'
    magenta: '#cb1ed1'
    cyan:    '#0dcdcd'
    white:   '#dddddd'

  # Bright colors
  bright:
    black:   '#767676'
    red:     '#f2201f'
    green:   '#23fd00'
    yellow:  '#fffd00'
    blue:    '#1a8fff'
    magenta: '#fd28ff'
    cyan:    '#14ffff'
    white:   '#ffffff'
