#!/bin/bash

formats=(
"tarz (tar.zst)"
"tarx (tar.xz)"
"targ (tar.gz)"
"tarb (tar.bz2)"
"7zip (.7z)"
"zip (.zip)"
)

# Use fzf to select the archive format
selected_format=$(printf "%s\n" "${formats[@]}" | fzf --prompt="Select format: ")

# If no format is selected, exit immediately
if [ -z "$selected_format" ]; then
    exit 0
fi

# Extract type and extension from the selected format
type="${selected_format%% (*}"
extension="${selected_format##* (}"  # Remove everything up to and including " ("
extension="${extension%\)}"  # Remove the closing parenthesis

echo " "
read -rp "Enter the name for the $extension archive or press Enter to exit: " archive_name

if [ -z "$archive_name" ]; then
    echo -e "Exiting script as no archive name was provided.\n"
    exit 0
fi

archive_name=$(echo "$archive_name" | tr -d '/')

# Function to show progress bar
show_progress() {
    local pid=$1
    local delay=0.2
    local spinstr='|/-\'
    while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
        local temp=${spinstr#?}
        printf " [%c]  " "$spinstr"
        local spinstr=$temp${spinstr%"$temp"}
        sleep $delay
        printf "\b\b\b\b\b\b"
    done
    printf "    \b\b\b\b"
}

echo -e "\nCompressing files... (Ctrl+c:cancel)"

case $type in
    "tarz") 
        (tar --zstd -cf "$archive_name.tar.zst" "$@" &> /dev/null) &
        show_progress $!
        ;;
    "tarx") 
        (tar -Jcvf "$archive_name.tar.xz" "$@" &> /dev/null) &
        show_progress $!
        ;;
    "targ") 
        (tar -czf "$archive_name.tar.gz" "$@" &> /dev/null) &
        show_progress $!
        ;;
    "tarb") 
        (tar -cjvf "$archive_name.tar.bz2" "$@" &> /dev/null) &
        show_progress $!
        ;;
    "7zip") 
        (7z a "$archive_name.7z" "$@" &> /dev/null) &
        show_progress $!
        ;;
    "zip") 
        (zip -r "$archive_name.zip" "$@" &> /dev/null) &
        show_progress $!
        ;;
esac

if [ $? -ne 0 ]; then
    echo -e "\nCompression failed!\n"
else
    if [[ "$type" == "zip" || "$type" == "7zip" ]]; then
        echo -e "\nCompression successful! Archive created: ${archive_name}${extension}\n"
    else
        echo -e "\nCompression successful! Archive created: ${archive_name}.${extension}\n"
    fi
fi

read -rp "Press Enter to exit..."
