#! /bin/sh

modprobe zram
#It is important to set compression alg before the creation of zram device otherwise default compression alg is always used.
 echo zstd > /sys/block/zram0/comp_algorithm
wait
 echo 4G > /sys/block/zram0/disksize
wait
 mkswap --label zram0 /dev/zram0
wait
 swapon --priority 100 /dev/zram0
wait

exit
