#! /bin/sh

#Total sytem ram
RAM_GB=$(free -g | grep Mem: | awk '{print $2}')
#Division number, 2 is using around 50% of your ram as zram
var=2
#Resulted zram size in GBs
res=$((RAM_GB / var))
border=0

wait
modprobe zram
wait
echo zstd > /sys/module/zswap/parameters/compressor
#It is important to set compression alg before the creation of zram device otherwise default compression alg is always used.
 echo zstd > /sys/block/zram0/comp_algorithm
wait

#If size > 0 echoing the resulted zram size along with a G for gigabyte
if [ $res != $border ] 

then

echo -e "$res""G" > /sys/block/zram0/disksize ;

fi
 

wait
 mkswap --label zram0 /dev/zram0
wait
 swapon --priority 100 /dev/zram0
wait

exit
