#!/bin/bash

fragmentation=$(sudo e4defrag -c /mnt/D/ | grep "defragmentation"| cut -c 41-57)
SUB="does not need defragmentation"

if [[ "$fragmentation" == *"$SUB"* ]]; then
	
	sudo -u siyia DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus notify-send "ext4 partition /mnt/D/ does not need defragmentation"
	
else

    e4defrag /mnt/D/
fi
