#!/bin/bash

fragmentation=$(sudo e4defrag -c your_mount_point | grep "defragmentation")
#fragmentation2=$(sudo e4defrag -c your_mount_point2 | grep "defragmentation")

SUB="does not need defragmentation"

if [[ "$fragmentation" == *"$SUB"* ]]; then
	
	sudo -u your_user DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/your_user_id/bus notify-send "ext4 partition your_mount_point does not require defragmentation"
	
else

    e4defrag your_mount_point
fi


#if [[ "$fragmentation2" == *"$SUB"* ]]; then
	
#	sudo -u your_user DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/your_user_id/bus notify-send "ext4 partition your_mount_point2 does not require defragmentation"
	
#else

#    e4defrag your_mount_point2
#fi
