[[manager.prepend_keymap]]
on = ["c"]
run = "unyank"
desc = "Clear yanked files"

[[manager.prepend_keymap]]
on = ["<C-c>"]
run = "escape --all"
desc = "Clear selection"

[[manager.prepend_keymap]]
on = ["<C-f>"]
run = "search fd --args='-e -H'"
desc = "Search"

[[manager.prepend_keymap]]
on = ["f"]
run = "filter --smart"
desc = "Filter"

[[manager.prepend_keymap]]
on   = [ "z" ]
run  = "plugin compress"
desc = "Archive selected files"

[[manager.prepend_keymap]]
on = ["d"]
run = "yank --cut"
desc = "Cut"

[[manager.prepend_keymap]]
on = ["<C-a>"]
run = "toggle_all --state=none"
desc = "Toggle between select all and clear selection"

[[manager.prepend_keymap]]
on = ["<Delete>"]
run = "remove --permanently"
desc = "remove"

[[manager.prepend_keymap]]
 on = ["n", "f"]
run = "create file"
desc = "Create a new file"

[[manager.prepend_keymap]]
on = ["l"]
run = "link --relative"
desc = "Create a new symlink from yanked files/folders"

[[manager.prepend_keymap]]
on = ["n", "d"]
run = "create dir"
desc = "Create a new directory"

[[manager.prepend_keymap]]
on = ["x"]
run = "cancel"
desc = "Cancel task"

[[manager.prepend_keymap]]
on   = [ "<F1>" ]
run  = "cd ~/"
desc = "Cd to ~/"

[[manager.prepend_keymap]]
on   = [ "<F2>" ]
run  = "cd /mnt/D/"
desc = "Cd to /mnt/D/"

[[manager.prepend_keymap]]
on   = [ "<F3>" ]
run  = "cd /mnt/"
desc = "Cd to /mnt/"

[[manager.prepend_keymap]]
on   = [ "<F4>" ]
run  = "cd /run/media/"
desc = "Cd to /run/media/"

[[manager.prepend_keymap]]
on   = [ "M" ]
run  = "shell '/home/siyia/.config/yazi/scripts/nmount' --block"
desc = "Mount/Unmount usb drives"

[[manager.prepend_keymap]]
on   = [ "<F9>" ]
run  = "shell 'kitty' --orphan"
desc = "Launch terminal"

[[manager.prepend_keymap]]
on   = [ "e" ]
run  = '''shell 'micro "$0"' --block'''
desc = "Edit in terminal"
