[opener]
edit_with_geany = [
    { run = 'geany "$@"', orphan = true, for = "unix" },
]

[open]
prepend_rules = [
    { mime = "text/plain", use = [ "edit_with_geany" ] },
    { mime = "text/c", use = [ "edit_with_geany" ] },
    
]
