[mgr]
linemode = "mtime"

[opener]
open_with_zed = [    { run = 'rm -rf ~/.local/share/zed/db && zeditor "%s"', orphan = true, for = "unix" },
]
edit = [
    { run = '$EDITOR "%s"', block = true, for = "unix" },
]
open = [
    { run = 'xdg-open "%s"', desc = "Open" },
]
open_with_swayimg = [
    { run = 'swayimg "%s"', orphan = true, for = "unix" },
]
open_passwd = [
    { run = 'keepassxc "%s"', orphan = true, for = "unix" },
]
open_pdf = [
    { run = 'zathura "%s"', orphan = true, for = "unix" },
]

[open]
prepend_rules = [
    { name = "*.{txt,c,h,lua,cpp,toml,log,json}", mime = "text/*", use = ["open_with_zed", "edit"] },
    { mime = "text/*", use = [ "open_with_zed", "edit" ] },
    { name = "*.kdbx", mime = "application/octet-stream", use = ["open_passwd"] },
    { name = "*.pdf", mime = "application/pdf", use = ["open_pdf"] },
    { name = "*.{png,jpg,jpeg,gif,bmp,tiff,webp,svg}", mime = "image/*", use = ["open_with_swayimg"] },
    { mime = "application/xz", use = [ "extract_custom" ] },
    { mime = "application/bz", use = [ "extract_custom" ] },
    { mime = "application/bz2", use = [ "extract_custom" ] },
    { mime = "application/7z-compressed", use = [ "extract_custom" ] },
    { mime = "application/tar", use = [ "extract_custom" ] },
    { mime = "application/gzip", use = [ "extract_custom" ] },
    { mime = "application/zstd", use = [ "extract_custom" ] },
    { mime = "application/zip", use = [ "extract_custom" ] },
]
