[manager]
linemode = "mtime"

[opener]
edit_with_geany = [
    { run = 'geany "$@"', orphan = true, for = "unix" },
]

edit = [
	{ run = '$EDITOR "$@"', block = true, for = "unix" },
]

open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]

open_with_roller = [
    { run = 'file-roller "$@"', orphan = true, for = "unix" },
]

open_with_swayimg = [
    { run = 'swayimg "$@"', orphan = true, for = "unix" },
]

extract_here = [
	{ run = 'ya pub extract --list "$@"', desc = "extract here", for = "unix"},
]

open_passwd = [
    { run = 'keepassxc "$@"', orphan = true, for = "unix" },
]


[open]
prepend_rules = [
	{ name = "*.{txt,c,h,lua,cpp,toml,log}", use = [ "edit_with_geany", "edit" ] },
    { name = "*.kdbx", use = [ "open_passwd" ] },
    { name = "*.{png,jpg,jpeg,gif,bmp,tiff,webp,svg}", use = [ "open_with_swayimg" ] },
    { mime = "application/xz", use = [ "open_with_roller" , "extract_here" ] },
    { mime = "application/bz", use = [ "open_with_roller" , "extract_here" ] },
    { mime = "application/bz2", use = [ "open_with_roller" , "extract_here" ] },
    { mime = "application/7z-compressed", use = [ "open_with_roller" , "extract_here" ] },
    { mime = "application/tar", use = [ "open_with_roller" , "extract_here" ] },
    { mime = "application/gzip", use = [ "open_with_roller", "extract_here" ] },
    { mime = "application/zstd", use = [ "open_with_roller" , "extract_here" ] },
    { mime = "application/zip", use = [ "open_with_roller" , "extract_here" ] },
    
]

