[opener]
edit_with_geany = [
    { run = 'geany "$@"', orphan = true, for = "unix" },
]

open_with_roller = [
    { run = 'file-roller "$@"', orphan = true, for = "unix" },
]

extract_here = [
	{ run = 'ya pub extract --list "$@"', desc = "extract here", for = "unix"},
]

[open]
prepend_rules = [
    { mime = "text/plain", use = [ "edit_with_geany" ] },
    { mime = "text/c", use = [ "edit_with_geany" ] },
    { mime = "application/xz", use = [ "edit_with_geany" , "extract_here" ] },
    { mime = "application/7z", use = [ "edit_with_geany" , "extract_here" ] },
    { mime = "application/tar", use = [ "open_with_roller" , "extract_here" ] },
    { mime = "application/gzip", use = [ "open_with_roller", "extract_here" ] },
    { mime = "application/zstd", use = [ "open_with_roller" , "extract_here" ] },
    { mime = "application/zip", use = [ "open_with_roller" , "extract_here" ] },
    
]
