#!/bin/bash

clear;

formats=(
"tarx (tar.xz)"
"targ (tar.gz)"
"tarz (tar.zst)"
"7zip (.7z)"
"zip (.zip)"
)

echo "Choose the archive format:"
for i in "${!formats[@]}"; do
    printf "%d) %s\n" "$((i+1))" "${formats[$i]}"
done

echo " "

read -p "Enter your choice (1-${#formats[@]}) or any other key to exit: " choice

echo " "

if [[ "$choice" =~ ^[1-${#formats[@]}]$ ]]; then
    choice=$((choice-1))
    type="${formats[$choice]%% (*}"
    extension=".${formats[$choice]##* (}"
else
    echo "Exiting script."
    exit 0
fi

read -p "Enter the name for the $extension archive: " archive_name

echo " "

if [ -e "$archive_name$extension" ]; then
    echo " "
    echo "Error: File or directory $archive_name.$extension already exists."
    exit 1
fi

mkdir "$archive_name"
cp -r "$@" "$archive_name"

case $type in
    "tarx") tar -Jcvf "$archive_name.tar.xz" "$archive_name" ;;
    "targ") tar -czf "$archive_name.tar.gz" "$archive_name" ;;
    "tarz") env ZSTD="-6" tar --zstd -cf "$archive_name.tar.zst" "$archive_name" ;;
    "7zip") 7z a "$archive_name.7z" "$archive_name" ;;
    "zip") zip -r "$archive_name.zip" "$archive_name";;
esac

echo " "

[ $? -ne 0 ] && echo "Compression failed!" || echo "Compression successful! Archive created: $archive_name$extension"

rm -rf "$archive_name"

echo " "

read -p "Press Enter to exit..."

