#!/bin/bash

formats=(
"tarx (tar.xz)"
"targ (tar.gz)"
"tarz (tar.zst)"
"7zip (.7z)"
"zip (.zip)"
)

choice="$(printf '%s\n' "${formats[@]}" | fzf)" || exit 1
read -r type extension < <(awk -F '[()]' '{print $1,$2}' <<< "$choice")
read -p "Enter the name for the $extension archive: " archive_name
cd "$(realpath -f "$1")"

if [ -e "$archive_name$extension" ]; then
	echo " "
	echo "Error: File or directory $archive_name.$extension already exists."
	exit 1
fi

case $type in
			"tarx")
	            mkdir "$archive_name"
	            cp -r "$@" "$archive_name"
	            tar -Jcvf "$archive_name.tar.xz" "$archive_name"
	            rm -rf "$archive_name"
				echo " "
	            echo "Compression successful! Archive created: $archive_name.tar.xz"
	            ;;
	        "targ")
	            mkdir "$archive_name"
	            cp -r "$@" "$archive_name"
	            tar -czf "$archive_name.tar.gz" "$archive_name"
	            rm -rf "$archive_name"
				echo " "
	            echo "Compression successful! Archive created: $archive_name.tar.gz"
	            ;;
	        "tarz")
	            mkdir "$archive_name"
	            cp -r "$@" "$archive_name"
	            env ZSTD="-6" tar --zstd -cf "$archive_name.tar.zst" "$archive_name"
	            rm -rf "$archive_name"
				echo " "
	            echo "Compression successful! Archive created: $archive_name.tar.zst"
	            ;;
	        "7zip")
	            mkdir "$archive_name"
	            cp -r "$@" "$archive_name"
	            7z a "$archive_name.7z" "$archive_name"
	            rm -rf "$archive_name"
				echo ""
	            echo "Compression successful! Archive created: $archive_name.7z"
	            ;;
	        "zip")
	            mkdir "$archive_name"
	            cp -r "$@" "$archive_name"
	            zip -r "$archive_name.zip" "$archive_name"
	            rm -rf "$archive_name"
				echo " "
	            echo "Compression successful! Archive created: $archive_name.zip"
	            ;;
esac

[ $? -ne 0 ] && echo "Compression failed!" || echo "Compression successful! Archive created: $archive_name$extension"
